l=[10,20,30,40,50]
# print(l)
# print(l[2])
# print(l[-1])
# l.append(100)
# print(l)
# l.insert(2,40)
# print(l)
# print(15 in l)
# print(l.count(40))
# print(l.index(100))
# print(l.index(40,4,7))
# l.remove(20)
# print(l)
# print(l.pop())
# print(l)
# print(l.pop(4))
# print(l)
# del l[0]
# print(l)
# del l[0:2]
# print(l)
print(max(l))
print(min(l))
print(sum(l))
l.reverse()
print(l)
l.sort()
print(l)